In [5]:
import pandas as pd
df = pd.read_csv("../data/customer_support_tickets.csv")
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [6]:
df.columns

Index(['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age',
       'Customer Gender', 'Product Purchased', 'Date of Purchase',
       'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status',
       'Resolution', 'Ticket Priority', 'Ticket Channel',
       'First Response Time', 'Time to Resolution',
       'Customer Satisfaction Rating'],
      dtype='object')

In [10]:
df.dropna(inplace=True)

In [8]:
import nltk, re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = word_tokenize(text)
    return " ".join([w for w in words if w not in stop_words])

df['cleaned'] = df['ticket'].apply(preprocess)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

KeyError: 'ticket'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['cleaned'])

In [11]:
df.columns

Index(['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age',
       'Customer Gender', 'Product Purchased', 'Date of Purchase',
       'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status',
       'Resolution', 'Ticket Priority', 'Ticket Channel',
       'First Response Time', 'Time to Resolution',
       'Customer Satisfaction Rating'],
      dtype='object')

In [12]:
df.rename(columns={
    "Ticket Description": "ticket",
    "Ticket Type": "category",
    "Ticket Priority": "priority"
}, inplace=True)

In [15]:
df = df[['ticket', 'category', 'priority']].copy()
df.head()

,ticket,category,priority
2,I'm facing a problem with my {product_purchase...,Technical issue,Low
3,I'm having an issue with the {product_purchase...,Billing inquiry,Low
4,I'm having an issue with the {product_purchase...,Billing inquiry,Low
10,I'm having an issue with the {product_purchase...,Cancellation request,High
11,I'm having an issue with the {product_purchase...,Product inquiry,High

In [16]:
df.dropna(inplace=True)

In [20]:
import nltk, re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words =text.split()
    return " ".join([w for w in words if w not in stop_words])

df['cleaned'] = df['ticket'].apply(preprocess)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [18]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [19]:
df['cleaned'] = df['ticket'].apply(preprocess)

In [26]:
import nltk, re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    return " ".join([w for w in words if w not in stop_words])

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\BASHA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [31]:
df['cleaned'] = df['ticket'].apply(preprocess)

In [32]:
df[['ticket', 'cleaned']].head()

,ticket,cleaned
2,I'm facing a problem with my {product_purchase...,im facing problem productpurchased productpurc...
3,I'm having an issue with the {product_purchase...,im issue productpurchased please assist proble...
4,I'm having an issue with the {product_purchase...,im issue productpurchased please assist note s...
10,I'm having an issue with the {product_purchase...,im issue productpurchased please assist produc...
11,I'm having an issue with the {product_purchase...,im issue productpurchased please assist possib...

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['cleaned'])

In [34]:
from sklearn.linear_model import LogisticRegression

model_cat = LogisticRegression(max_iter=1000)
model_cat.fit(X, df['category'])

model_pri = LogisticRegression(max_iter=1000)
model_pri.fit(X, df['priority'])

LogisticRegression(max_iter=1000)

In [35]:
import joblib

joblib.dump(model_cat, "../model/category_model.pkl")
joblib.dump(model_pri, "../model/priority_model.pkl")
joblib.dump(vectorizer, "../model/vectorizer.pkl")

FileNotFoundError: [Errno 2] No such file or directory: '../model/category_model.pkl'

In [37]:
import os
import joblib

os.makedirs("../model", exist_ok=True)

joblib.dump(model_cat, "../model/category_model.pkl")
joblib.dump(model_pri, "../model/priority_model.pkl")
joblib.dump(vectorizer, "../model/vectorizer.pkl")

['../model/vectorizer.pkl']